In [35]:
# The np.array() function can take a list or list of lists as input. When we input a list, we get a one-dimensional array as a result:
vector = np.array([5, 10, 15, 20]) # list->ndarray
# When we input a list of lists, we get a matrix as a result:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
triple_matrix = np.array([[[1,2,3], [4,5,6], [7,8,9], [0,1,2], [0,1,2], [0,1,2], [0,1,2], [0,1,2], [0,1,2]]])
print(vector)
print()
print(matrix)
print()
print(triple_matrix, '\n')
print(triple_matrix.ndim)

[ 5 10 15 20]

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]] 

3


In [34]:
# We can use the ndarray.shape property to figure out how many elements are in the array
vector = np.array([1, 2, 3, 4]) #  一位数组-->行向量
print(vector.shape) # 表达向量或者矩阵的结构 在神经网络的测试环节很有用处 方便理解 debug
print()
print(vector.ndim, '\n')
# For matrices, the shape property contains a tuple with 2 elements.
matrix = np.array([[5, 10, 15], [20, 25, 30]]) # 二维数组->矩阵 2行3列
print(matrix.ndim, '\n')
print(type(matrix))
print(matrix.shape)
matrix.dtype


(4,)

1 

2 

<class 'numpy.ndarray'>
(2, 3)


dtype('int32')

In [ ]:
# When NumPy can't convert a value to a numeric data type like float or integer, it uses a special nan value that stands for Not a Number
# NAN is the missing data
# 1.98600000e+03 is actually 1.986 * 10 ^ 3

world_alcohol

array([['Year', 'WHO region', 'Country', 'Beverage Types',
        'Display Value'],
       ['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1987', 'Africa', 'Malawi', 'Other', '0.75'],
       ['1989', 'Americas', 'Bahamas', 'Wine', '1.5'],
       ['1985', 'Africa', 'Malawi', 'Spirits', '0.31']], dtype='<U52')

world_alcohol = np.genfromtxt("world_alcohol.txt", delimiter=",", dtype="U75", skip_header=1)

print(world_alcohol)

In [32]:
matrix = np.array([[5, 10, 15], [20, 25, 30],[35, 40, 45],[120, 340, 320]])
print(matrix.shape)
print()
print(matrix.ndim, '\n')
print(matrix[:,2])   #[:,]表示所有的行 取其中的一列
print()
print(matrix[:,1])
print()
print(matrix[:,0])
print()
print(matrix[1,:])
print()
print(matrix[2,:])

(4, 3)

2 

[ 15  30  45 320]

[ 10  25  40 340]

[  5  20  35 120]

[20 25 30]

[35 40 45]


In [21]:
matrix = np.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
# print(matrix[:,1]) [10 25 40]
print(matrix[:,0:2]) # [:,0:2]所有样本 取两列 第零列和第一列
print()
print(matrix[:,1:2])
print()
print(matrix[1:2,1:2])
print()
print(matrix[1:3,1:2])
print()
print(matrix[0:3,0:2])

[[ 5 10]
 [20 25]
 [35 40]]

[[10]
 [25]
 [40]]

[[25]]

[[25]
 [40]]

[[ 5 10]
 [20 25]
 [35 40]]


In [25]:
# it will compare the second value to each element in the vector
# If the values are equal, the Python interpreter returns True; otherwise, it returns False
vector = np.array([5, 10, 15, 20])
# vector == 15 # 对其中每个元素都进行操作

print(vector==15)


[False False  True False]


In [29]:
# We can convert the data type of an array with the ndarray.astype() method.
vector = np.array(["1", "2", "3"])
print(vector.dtype)
print(vector, '\n')
vector = vector.astype(float)
print(vector.dtype)
print(vector)


<U1
['1' '2' '3'] 

float64
[1. 2. 3.]


In [37]:
vector = np.array([5, 10, 15, 20])
# vector.min()
# vector.sum()
# print(help(np.array))
x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
# x['a']
print(x.dtype)
x['b']


[('a', '<i4'), ('b', '<i4')]


array([2, 4])

In [ ]:
import numpy as np

world_alcohol = np.genfromtxt("world_alcohol.txt", delimiter=",", dtype=str)
print(type(world_alcohol))
print(world_alcohol) # ndarray
print(help(np.genfromtxt))

In [42]:
import numpy as np

print(np.__version__)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

In [45]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [47]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [50]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [ ]:
import numpy as np
np.info(np.ndarray)    #get the related infomation about (XXX)

In [52]:
# 创建一个长度为5并且除了第3个值为1的空向量
z = np.zeros(5)
z[2] = 1
print(z)

[0. 0. 1. 0. 0.]


In [61]:
# 创建一个值域范围从10到49的向量
# 反转一个向量(第一个元素变为最后一个
# import numpy as np
z = np.arange(10, 50)
z1 = z[::-1]
print(z,'\n\n',z1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [62]:
# 创建一个 3x3 并且值从0到8的矩阵
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [63]:
# 找到数组[1,2,0,0,4,0]中非0元素的位置索引
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int32),)


In [64]:
# 创建一个 3x3 的单位矩阵
m = np.eye(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [70]:
# 创建一个 3x3x3的随机数组 
m1 = np.random.random((2,3,2))
print(m1)
# m1 = np.random((3,3))
# print(m1)
m2 = np.random.random((3,3,3))
print(m2,'\n')

[[[0.38469311 0.74195642]
  [0.6382349  0.53783267]
  [0.69321525 0.80500195]]

 [[0.61627717 0.06918821]
  [0.04656859 0.2042294 ]
  [0.04318968 0.22912995]]]
[[[0.49379058 0.41798999 0.41552498]
  [0.81285047 0.14440705 0.04164441]
  [0.15254411 0.62814312 0.48845156]]

 [[0.85051126 0.17054674 0.56215459]
  [0.11174541 0.60066222 0.38488376]
  [0.08162322 0.51068039 0.41070433]]

 [[0.66400666 0.5686297  0.19351253]
  [0.07583558 0.16914522 0.30092034]
  [0.876882   0.94645745 0.24484153]]] 



In [73]:
# 创建一个 10x10 的随机数组并找到它的最大值和最小值
z = np.random.random((5,5))
print(z)
zmin, zmax = z.min(), z.max()
print(zmin, zmax)

[[0.16084973 0.91812517 0.56471032 0.24156685 0.14269052]
 [0.21995644 0.96235967 0.38015336 0.67663003 0.19853331]
 [0.40277486 0.70062202 0.22892213 0.1054155  0.33161849]
 [0.84435626 0.61336605 0.24430485 0.82379611 0.14638389]
 [0.30356474 0.38143167 0.17955074 0.82404608 0.52829021]]
0.1054155019467522 0.9623596727771797


In [78]:
z = np.random.random((3,3))
print(z,'\n\n',z*10)
zmin, zmax = z.min(), z.max()
print(zmin, zmax)

[[0.88883613 0.65542983 0.31380294]
 [0.20567609 0.50294344 0.16614589]
 [0.40203786 0.72307135 0.9051727 ]] 

 [[8.88836127 6.5542983  3.13802943]
 [2.05676092 5.02943441 1.66145886]
 [4.02037857 7.23071352 9.051727  ]]
0.16614588560035393 0.9051726998167513


In [79]:
# 创建一个长度为10的随机向量并找到它的平均值
z = np.random.random(10)
m = z.mean()
print(m)

0.5828986687924791


In [83]:
#  创建一个二维数组，其中边界值为1，其余值为0
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [84]:
# 对于一个存在在数组，如何添加一个用0填充的边界
# Z = np.ones((5,5))
# Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
# print(Z)

Z = np.zeros((6,6))
Z[1:-1,1:-1] = 1
print(Z)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [106]:
print(0.3 == 3 * 0.1, '\n')
print(0 == 0.3 * 0, '\n')
print(0.5 == 1 / 2, '\n')
a = 1
b = 0.1 * 10
print(a == b, '\n')
print(0.2 == 2 * 0.1)
print(0.3 == 0.1 * 3)
print(0.4 == 4 * 0.1)
print(0.5 == 5 * 0.1)
print(0.6 == 6 * 0.1)
print(0.7 == 7 * 0.1)
print(0.8 == 8 * 0.1)
print(0.9 == 9 * 0.1)

False 

True 

True 

True 

True
False
True
True
False
False
True
True


In [108]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

nan
False
False
nan


In [110]:
# 创建一个 3x3的矩阵，并设置值1,2,3,4落在其对角线下方位置
Z = np.diag(1+np.arange(3),k=-1)
print(Z)

[[0 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [112]:
# 创建一个4x4 的矩阵，并且设置成棋盘样式
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
