In [1]:
import pandas as pd
obj = pd.Series([4, 5, 7, -3])
print(obj)
print()
print(obj.values)
print(obj.index)


0    4
1    5
2    7
3   -3
dtype: int64

[ 4  5  7 -3]
RangeIndex(start=0, stop=4, step=1)


In [4]:
obj1 = pd.Series([4, 5, 7, -3], index = [1, 2, 3, 4])
print(obj1,'\n')
print(obj1.index)

1    4
2    5
3    7
4   -3
dtype: int64 

Int64Index([1, 2, 3, 4], dtype='int64')


In [10]:
import numpy as np
obj1 = pd.Series([4, 5, 7, -3], index = ['a', 'b', 'c', 'd'])
print(obj1,'\n')
print(obj1.index,'\n')
print(obj1['b'])
print(obj1[obj1 > 4], '\n')
print(np.exp(obj1))    # numpy and pandas together for calculation

a    4
b    5
c    7
d   -3
dtype: int64 

Index(['a', 'b', 'c', 'd'], dtype='object') 

5
b    5
c    7
dtype: int64 

a      54.598150
b     148.413159
c    1096.633158
d       0.049787
dtype: float64


In [11]:
'd' in obj1

True

In [12]:
'e' in obj1

False

In [24]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj2 = pd.Series(sdata)
print(obj2, '\n')
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj3 = pd.Series(sdata, index = states)
# print(obj3, '\n')
print(obj3, '\n')
print(pd.notnull(obj2), '\n')
print(pd.isnull(obj3), '\n')  # the terms “missing” or “NA” interchangeably to refer to missing data
                            # "isnull" and "notnull" to check missing or not
# print(pd.notnull(obj3), '\n')
print(obj3.isnull(), '\n')
print(obj2 + obj3)


Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64 

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64 

Ohio      True
Texas     True
Oregon    True
Utah      True
dtype: bool 

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool 

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool 

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64


In [25]:
obj3.name = 'population'
obj3.index.name = 'state'
print(obj3)

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64


In [26]:
obj2.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
print(obj2)

Bob      35000
Steve    71000
Jeff     16000
Ryan      5000
dtype: int64


In [29]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
         'year': [2000, 2001, 2002, 2001, 2002, 2003],
          'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
print(frame, '\n')
print(frame.head(), '\n')
frame1 = pd.DataFrame(data, columns=['year', 'state', 'pop'])
print(frame1)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2 

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9 

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2


In [41]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
....: index=['one', 'two', 'three', 'four',
....: 'five', 'six'])
print(frame2, '\n')
print(frame2.columns, '\n')
print(frame2['state'], '\n')
print(frame2.year, '\n')
print(frame2.state, '\n')
print(frame2.pop, '\n')
print(frame2.debt)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN 

Index(['year', 'state', 'pop', 'debt'], dtype='object') 

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object 

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64 

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object 

<bound method NDFrame.pop of        year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN> 

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: debt, dtype: object


In [44]:
print(frame2.loc["three"], '\n')
frame2['debt'] = 23.3
print(frame2)

year     2002
state    Ohio
pop       3.6
debt     23.3
Name: three, dtype: object 

       year   state  pop  debt
one    2000    Ohio  1.5  23.3
two    2001    Ohio  1.7  23.3
three  2002    Ohio  3.6  23.3
four   2001  Nevada  2.4  23.3
five   2002  Nevada  2.9  23.3
six    2003  Nevada  3.2  23.3


In [ ]:
help(frame.loc)

In [63]:
frame2['debt'] = np.arange(3, 29, 5)
print(frame2)


       year   state  pop  debt
one    2000    Ohio  1.5     3
two    2001    Ohio  1.7     8
three  2002    Ohio  3.6    13
four   2001  Nevada  2.4    18
five   2002  Nevada  2.9    23
six    2003  Nevada  3.2    28


In [ ]:
help(np.arange)

In [66]:
frame2['eastern'] = frame2.state == 'Ohio'
print(frame2, '\n')
del frame2['eastern']     # delete a column from the data
print(frame2, '\n')
print(frame2.columns)

       year   state  pop  debt  eastern
one    2000    Ohio  1.5     3     True
two    2001    Ohio  1.7     8     True
three  2002    Ohio  3.6    13     True
four   2001  Nevada  2.4    18    False
five   2002  Nevada  2.9    23    False
six    2003  Nevada  3.2    28    False 

       year   state  pop  debt
one    2000    Ohio  1.5     3
two    2001    Ohio  1.7     8
three  2002    Ohio  3.6    13
four   2001  Nevada  2.4    18
five   2002  Nevada  2.9    23
six    2003  Nevada  3.2    28 

Index(['year', 'state', 'pop', 'debt'], dtype='object')


In [69]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
....:    'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
print(frame3, '\n')
print(frame3.T)

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6 

        2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6


In [71]:
pdata = {'Ohio': frame3['Ohio'][:-1],
....:  'Nevada': frame3['Nevada'][:2]}
frame4 = pd.DataFrame(pdata)
print(frame4)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4


In [77]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
print(frame3)

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6


In [78]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [79]:
frame2.values

array([[2000, 'Ohio', 1.5, 3],
       [2001, 'Ohio', 1.7, 8],
       [2002, 'Ohio', 3.6, 13],
       [2001, 'Nevada', 2.4, 18],
       [2002, 'Nevada', 2.9, 23],
       [2003, 'Nevada', 3.2, 28]], dtype=object)

In [86]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
print(obj, '\n')
index = obj.index
print(index, '\n')
labels = pd.Index(np.arange(3))
print(labels, '\n')
obj1 = pd.Series([1.5, -2.5, 0], index=labels)
print(obj1, '\n')
obj1.index is labels

a    0
b    1
c    2
dtype: int64 

Index(['a', 'b', 'c'], dtype='object') 

Int64Index([0, 1, 2], dtype='int64') 

0    1.5
1   -2.5
2    0.0
dtype: float64 



True

In [87]:
# Unlike Python sets, a pandas Index can contain duplicate labels:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
print(dup_labels)

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')


In [89]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
print(obj, '\n\n', obj2)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64 

 a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64


In [90]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
print(obj, '\n')
print(obj2)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64 

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64


In [93]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
l = obj3.reindex(range(6), method='ffill')  # The method option allows us to do this, using a
                                            # method such as ffill, which forward-fills the values
print(obj3, '\n')
print(l)

0      blue
2    purple
4    yellow
dtype: object 

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object


In [98]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
....: index=['a', 'c', 'd'],
....: columns=['Ohio', 'Texas', 'California'])
print(frame,'\n')
print(frame.T, '\n')
frame


   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8 

            a  c  d
Ohio        0  3  6
Texas       1  4  7
California  2  5  8 



Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [97]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [99]:
states = ['Texas', 'Utah', 'California']


Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [104]:
frame3 = frame.reindex(columns=states)
print(frame, '\n')
print(frame3)

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8 

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8


In [105]:
frame4 = frame.loc[['a', 'b', 'c', 'd'], states]
frame4

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [108]:
# Dropping one or more entries from an axis is easy if you already have an index array or list without those entries. 
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
print(new_obj, "\n")
print(obj.drop(['d', 'c']))

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64 

a    0.0
b    1.0
e    4.0
dtype: float64


In [118]:
# Calling drop with a sequence of labels will drop values from the row labels (axis 0):
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
.....:     index=['Ohio', 'Colorado', 'Utah', 'New York'],
.....:   columns=['one', 'two', 'three', 'four'])
print(data, '\n')
print(data.drop(['Colorado', 'Ohio']), "\n")
print(data.drop('two', axis=1), '\n')　　　　　 　#  drop values from the columns by passing axis=1 or axis='columns'
#print(data.drop('two', axis='columns'))

SyntaxError: invalid syntax (<ipython-input-118-0cd51ef09018>, line 3)

In [119]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
.....:     index=['Ohio', 'Colorado', 'Utah', 'New York'],
.....:   columns=['one', 'two', 'three', 'four'])
print(data, '\n')

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15 



In [128]:
print(data.drop(['Colorado', 'Ohio']), "\n")
#  drop values from the columns by passing axis=1 or axis='columns'
# print(data.drop('two', axis=1))　　　　　
data.drop('two', axis=1)
# #print(data.drop('two', axis='columns'))

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15 



one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [129]:
print(data.drop('two', axis='columns'))

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15


In [130]:
print(obj.drop('c', inplace=True))

None


In [133]:
obj5 = obj.drop('b', inplace=True)
print(obj5)

None


In [134]:
ser = pd.Series(np.arange(3.))
print(ser)

0    0.0
1    1.0
2    2.0
dtype: float64


In [135]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
print(ser2)

a    0.0
b    1.0
c    2.0
dtype: float64


In [137]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
print(s1 + s2)

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64


In [138]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
.....: index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
.....: index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df1 + df2)

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN


In [139]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
.....: index=['three', 'one'],
.....: columns=['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [140]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4